### ISSUE TITLE
Remove Navigation icon for menus when fully displayed

### ISSUE THREAD

**Issue by Stacie-Seaman** [Shrinking-World/MyBook#10]
![nav](https://cloud.githubusercontent.com/assets/8845449/21571953/832cff94-ce91-11e6-9df4-85cd1e70b1d1.JPG)

**Comment by Mark-Seaman** [comment]
Remove Navigation icon for menus when fully displayed.  This is an artifact from the action menu.

**Comment by Stacie-Seaman** [comment]
DONE
