### ISSUE TITLE
Uploading a Resume results in an error message

### ISSUE THREAD

**Issue by ChristineSeaman** [Shrinking-World/MyBook#115]
While the Interview Candidate Details page loads normally and a file can be selected, pressing the Upload Resume button causes an error.

Same for the Upload Application.

**Comment by ChristineSeaman** [comment]
![screenshot from 2017-04-05](https://cloud.githubusercontent.com/assets/10851571/24720574/c0212966-19fa-11e7-8364-f48fedafd16f.png)

**Comment by ChristineSeaman** [comment]
Closed in error

**Comment by Stacie-Seaman** [comment]
Fixed
