### ISSUE TITLE
Editing an interviewer's info creates a second instance of that name instead

### ISSUE THREAD

**Issue by ChristineSeaman** [Shrinking-World/MyBook#124]

**Comment by ChristineSeaman** [comment]
Attempted to add a middle name to Shania Reed; pressed Save Interviewer button. This caused a duplicate record that is identical to the original values -- no changes were saved.

Attempted to add a phone number to the record, no changes were saved and no new records were created. Changing the name appears to be the main culprit.

**Comment by Stacie-Seaman** [comment]
Edit now only allows Manager to change Interviewer's email address.

Looks good.
