### ISSUE TITLE
Handle users not connected to Hiring Guru

### ISSUE THREAD

**Issue by Mark-Seaman** [Shrinking-World/MyBook#17]
My Book Online is the hosting app for Hiring Guru.  Users may be set up for other apps but not configured to use Hiring Guru.

Non-Hire user must be logged out automatically and sent to the Login screen for Hiring Guru.

**Comment by Stacie-Seaman** [comment]
Test with login for Todd?

**Comment by Stacie-Seaman** [comment]
DONE
