### ISSUE TITLE
Test all domain URLs for proper response

### ISSUE THREAD

**Issue by Mark-Seaman** [Shrinking-World/MyBook#57]
# Production Server

http://who2hire.co
http://www.who2hire.co
http://www.who2hire.co/hire

http://who2hire.biz
http://www.who2hire.biz
http://www.who2hire.biz/hire

http://who2hire.us
http://www.who2hire.us
http://www.who2hire.us/hire

# Staging Server

https://the-very-idea.us/hire/login

# Should not work

http://162.243.52.136/hire
http://hiring-guru.net

**Comment by Stacie-Seaman** [comment]
Tested and passed.
