### ISSUE TITLE
Forgot Password Scenario

### ISSUE THREAD

**Issue by Mark-Seaman** [Shrinking-World/MyBook#88]
When the user forgets their password they need a mechanism for resetting their own password.

Django support a password reset mechanism that does the following.

* In the login view there is a Reset password button.
* User enters email address
* User is sent a reset password token
* User clicks on reset link in email to go to change password view in Who2Hire
* User enters password twice
* New password is saved

This requires implementing the following views that we do not have:

- registration/password_reset_form.html
- registration/password_reset_subject.txt
- registration/password_reset_email.html
- registration/password_reset_done.html
- registration/password_reset_confirm.html
- registration/password_reset_complete.html

**Comment by Stacie-Seaman** [comment]
Looks great!
