### ISSUE TITLE
Turn off DEBUG flag

### ISSUE THREAD

**Issue by Mark-Seaman** [Shrinking-World/MyBook#89]

**Comment by Mark-Seaman** [comment]
I pushed this change to staging.  If all goes well it will go to production on Friday, March 31.

Report any Server Error 500 status errors.

**Comment by Stacie-Seaman** [comment]
I was logged in as a Superuser and clicked on Interviews > got 500 error

**Comment by Stacie-Seaman** [comment]
No server 500 errors over the last few days.
