### ISSUE TITLE
Job opening displays under Interviews but not under Job Openings

### ISSUE THREAD

**Issue by ChristineSeaman** [Shrinking-World/MyBook#97]
Steps to find strange behavior:

- Logged in as RonZ
- Selected 1st available job -- Sr Web Developer
- Used the "Edit Job Opening" and saved changes. Utilized the "Next Step" link at the bottom of the page to progress through the workflow.
- On the Skills Selection page, added a technical Skill. Selected the Next Step button (differed from hyperlink, but with same result).
- Made sure all skills had questions. Selected "Save as Template" option and saved with the name Senior Web Devoloper Template. Used "Next Step" to continue onwards.
- Completed all tasks for adding 3 new Candidates for the new opening and then processed an Interview for Fernando.

Observed Results:
Once the first interview was completed, I went to view the report. The new information was not available as a report, although I was able to get back to the completed interview questions, so the information was at least saved. Upon further investigation, it was found that two different instance had been created for the Senior Web Developer position. The first set had been created before I had started testing and was populated with Joe Smith. The second set was created through the incorrect usage of creating a template from the originally populate job opening. This set of interview session has the 3 candidates I created with the info for Fernando's interview, but was not visible anywhere else.

**Comment by Mark-Seaman** [comment]
This problem is now fixed.  Great find.  

After saving a template the sequence goes back to the job opening list so that a new Job Opening can be created.

**Comment by Stacie-Seaman** [comment]
Christine verified.
